name: Build
on:
  push:
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build Release APK
      run: ./gradlew assembleApkstoreDebug
    - name: show file
      run: find . -type f -iname "*.apk"
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: ./presentation/build/outputs/apk/apkstore/debug/presentation-apkstore-debug.apk
